FROM eclipse-temurin:17-jdk-focal


WORKDIR /app

ADD target/spring-boot-docker-0.0.1-SNAPSHOT.jar /app/spring-boot-docker-0.0.1-SNAPSHOT.jar


ENTRYPOINT ["java","-jar","spring-boot-docker-0.0.1-SNAPSHOT.jar"]